const List<Map<String, String>> kKurdishWords = [
  {'kurdish': 'Silav', 'english': 'Hello'},
  {'kurdish': 'Spas', 'english': 'Thank you'},
  {'kurdish': 'Navê te çî ye?', 'english': 'What is your name?'},
  {'kurdish': 'Ez ... im', 'english': 'I am ...'},
  {'kurdish': 'Çawa yî?', 'english': 'How are you?'},
  {'kurdish': 'Baş im', 'english': 'I am fine'},
  {'kurdish': 'Jîyan', 'english': 'Life'},
  {'kurdish': 'Bav', 'english': 'Father'},
  {'kurdish': 'Dayik', 'english': 'Mother'},
  {'kurdish': 'Xwişk', 'english': 'Sister'},
  {'kurdish': 'Bira', 'english': 'Brother'},
  {'kurdish': 'Pirtûk', 'english': 'Book'},
  {'kurdish': 'Pirtûk', 'english': 'Book'},
  {'kurdish': 'Xwendin', 'english': 'Reading'},
  {'kurdish': 'Nivîsandin', 'english': 'Writing'},
  {'kurdish': 'Ders', 'english': 'Lesson'},
  {'kurdish': 'Ziman', 'english': 'Language'},
  {'kurdish': 'Dost', 'english': 'Friend'},
  {'kurdish': 'Xwendevan', 'english': 'Student'},
  {'kurdish': 'Mamoste', 'english': 'Teacher'},
  {'kurdish': 'Pirtûk', 'english': 'Book'},
];
